using System;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class SampleIncrementalSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is TypeDeclarationSyntax,
                (ctx, _) => GetTypeDeclarationForSourceGen(ctx))
            .Where(t => t.reportAttributeFound)
            .Select((t, _) => t.Item1);

        context.RegisterSourceOutput(provider.Collect(), GenerateCode);
    }

    private static (TypeDeclarationSyntax, bool reportAttributeFound) GetTypeDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var typeDeclarationSyntax = (TypeDeclarationSyntax)context.Node;

        if (typeDeclarationSyntax is ClassDeclarationSyntax or StructDeclarationSyntax)
        {
            if (typeDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                // Go through all attributes of the class.
                foreach (AttributeListSyntax attributeListSyntax in typeDeclarationSyntax.AttributeLists)
                {
                    foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
                    {
                        if (ModelExtensions.GetSymbolInfo(context.SemanticModel, attributeSyntax).Symbol is not
                            IMethodSymbol
                            attributeSymbol)
                            continue; // if we can't get the symbol, ignore it

                        string attributeName = attributeSymbol.ContainingType.ToDisplayString();

                        if (attributeName == "CodeGeneration.Runtime.Visitor.VisitorAttribute")
                            return (typeDeclarationSyntax, true);
                    }
                }
            }
        }

        return (typeDeclarationSyntax, false);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<TypeDeclarationSyntax> typeDeclarations)
    {
        // Go through all filtered class declarations.
        MemoryStream sourceStream = new();
        StreamWriter sourceStreamWriter = new(sourceStream, Encoding.UTF8);
        IndentedTextWriter codeWriter = new (sourceStreamWriter);
        codeWriter.WriteLine("// <auto-generated/>");
        codeWriter.WriteLine("using UnityEngine;");
        
        codeWriter.WriteLine("namespace RoslynCodeGeneration");
        codeWriter.WriteLine('{');
        codeWriter.Indent++;

        codeWriter.WriteLine("public static class GeneratedCode");
        codeWriter.WriteLine('{');
        codeWriter.Indent++;

        codeWriter.WriteLine("[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
        codeWriter.WriteLine("public static void InitVisitors()");
        
        codeWriter.WriteLine('{');
        codeWriter.Indent++;
        foreach (var typeDeclarationSyntax in typeDeclarations)
        {
            codeWriter.Write("global::CodeGeneration.Runtime.Visitor.VisitorCall<");
            codeWriter.AppendFullTypeName(typeDeclarationSyntax);
            codeWriter.Write(">.Visit = ");
            codeWriter.AppendFullTypeName(typeDeclarationSyntax);
            codeWriter.Write(".Visit");
            codeWriter.WriteLine(";");
        }        
        codeWriter.Indent--;
        codeWriter.WriteLine('}');
        
        // Close the class.
        codeWriter.Indent--;
        codeWriter.WriteLine('}');
        
        // Close the namespace.
        codeWriter.Indent--;
        codeWriter.WriteLine('}');
        
        foreach (var typeDeclarationSyntax in typeDeclarations)
        {
            var parentInfos = GetFullTypeName(typeDeclarationSyntax);

            foreach (var parentInfo in parentInfos)
            {
                switch (parentInfo.Type)
                {
                    case ParentType.Namespace:
                        codeWriter.Write("namespace ");
                        break;
                    case ParentType.Class:
                        codeWriter.Write("public partial class ");
                        break;
                    case ParentType.Struct:
                        codeWriter.Write("public partial struct ");
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
                codeWriter.WriteLine(parentInfo.Name);
                codeWriter.WriteLine('{');
                codeWriter.Indent++;                
            }
            
            codeWriter.Write("public partial ");

            switch (typeDeclarationSyntax)
            {
                case StructDeclarationSyntax:
                    codeWriter.Write("struct ");
                    break;
                case ClassDeclarationSyntax:
                    codeWriter.Write("class ");
                    break;
            }
            
            codeWriter.WriteLine(typeDeclarationSyntax.Identifier.Text);
            codeWriter.WriteLine('{');
            codeWriter.Indent++;
            
            codeWriter.Write("public static void Visit");
            codeWriter.Write("(global::CodeGeneration.Runtime.Visitor.IVisitor visitor, ref ");
            codeWriter.AppendFullTypeName(typeDeclarationSyntax);
            codeWriter.WriteLine(" container)");
            codeWriter.WriteLine('{');
            codeWriter.Indent++;
            
            foreach (var member in typeDeclarationSyntax.Members)
            {
                if (member is FieldDeclarationSyntax fieldDeclarationSyntax)
                {
                    foreach (var declarationVariable in fieldDeclarationSyntax.Declaration.Variables)
                    {
                        codeWriter.Write("visitor.Visit(\"");
                        codeWriter.Write(declarationVariable.Identifier.Text);
                        codeWriter.Write("\", ref container.");
                        codeWriter.Write(declarationVariable.Identifier.Text);
                        codeWriter.WriteLine(");");
                    }
                }
                else if (member is PropertyDeclarationSyntax propertyDeclarationSyntax)
                {
                    codeWriter.Write("visitor.Visit(\"");
                    codeWriter.Write(propertyDeclarationSyntax.Identifier.Text);
                    codeWriter.Write("\", ref container.");
                    codeWriter.Write(propertyDeclarationSyntax.Identifier.Text);
                    codeWriter.WriteLine(");");
                }
            }
            
            codeWriter.Indent--;
            codeWriter.WriteLine('}');
            
            codeWriter.Indent--;
            codeWriter.WriteLine('}');

            for (var i = 0; i < parentInfos.Length; i++)
            {
                codeWriter.Indent--;
                codeWriter.WriteLine('}');
            }
        }
        
        sourceStreamWriter.Flush();
        
        // Add the source code to the compilation.
        context.AddSource("Visitor.g.cs", SourceText.From(sourceStream, Encoding.UTF8, canBeEmbedded: true));
    }

    public enum ParentType
    {
        None,
        Namespace,
        Class,
        Struct,
    }
    
    private struct ParentInfo
    {
        public string Name;
        public ParentType Type;
    }
    
    private ParentInfo[] GetFullTypeName(TypeDeclarationSyntax classDeclarationSyntax)
    {
        var ancestorCount = 0;
        var parent = classDeclarationSyntax.Parent;
        while (parent is BaseNamespaceDeclarationSyntax or BaseTypeDeclarationSyntax)
        {
            ancestorCount++;
            parent = parent.Parent;
        }
        parent = classDeclarationSyntax.Parent;
        
        var infos = new ParentInfo[ancestorCount];
        var currentAncestor = ancestorCount - 1;
        while (parent is BaseNamespaceDeclarationSyntax or BaseTypeDeclarationSyntax)
        {
            ref var info = ref infos[currentAncestor]; 
            
            switch (parent)
            {
                case BaseTypeDeclarationSyntax parentClass:
                    info.Name = parentClass.Identifier.Text;

                    if (parentClass is ClassDeclarationSyntax)
                    {
                        info.Type = ParentType.Class;
                    }
                    else if (parentClass is StructDeclarationSyntax)
                    {
                        info.Type = ParentType.Struct;
                    }
                    
                    break;
                case BaseNamespaceDeclarationSyntax parentNamespace:
                    info.Name = parentNamespace.Name.ToString();
                    info.Type = ParentType.Namespace;
                    break;
            }

            currentAncestor--;
            parent = parent.Parent;
        }
        
        return infos;
    }
}

static class CodeWriterExtensions
{
    public static void AppendFullTypeName(this TextWriter codeWriter, TypeDeclarationSyntax classDeclarationSyntax)
    {
        var ancestorCount = 0;
        var parent = classDeclarationSyntax.Parent;
        while (parent is BaseNamespaceDeclarationSyntax or BaseTypeDeclarationSyntax)
        {
            ancestorCount++;
            parent = parent.Parent;
        }
        parent = classDeclarationSyntax.Parent;
        
        var names = new string[ancestorCount];
        var currentAncestor = ancestorCount - 1;
        while (parent is BaseNamespaceDeclarationSyntax or BaseTypeDeclarationSyntax)
        {
            switch (parent)
            {
                case BaseTypeDeclarationSyntax parentClass:
                    names[currentAncestor] = parentClass.Identifier.Text;
                    break;
                case BaseNamespaceDeclarationSyntax parentNamespace:
                    names[currentAncestor] = parentNamespace.Name.ToString();
                    break;
            }

            currentAncestor--;
            parent = parent.Parent;
        }

        codeWriter.Write("global::");
        foreach (var name in names)
        {
            codeWriter.Write(name);
            codeWriter.Write('.');
        }
        codeWriter.Write(classDeclarationSyntax.Identifier.Text);
    }
}